packages:
  - name: joke
    actions:
      - name: joke
        runtime: 'python:default'

  - name: joke
    actions:
      - name: hello
        runtime: 'python:default'

  - name: offer_order
    actions:
      - name: product
        runtime: 'python:default'

  - name: offer_order
    actions:
      - name: partner
        runtime: 'python:default'
